### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by rahat-yasir** [CongBao/ImageEnhancer#2]
Will you upload the pre-trained model, so that I can reproduce your results and try it.

**Comment by CongBao** [comment]
I've uploaded the pre-trained GRY model in this commit: 2b151e9a638db9197527a31f5c6a9a0ef4f8d8b7
Other models will be uploaded later since they were removed from the server and I have to train them again.
Please note the restriction in image shape. As the models were trained with images of shape (128, 128, 3), you can only train/process on your own images with the same shape.

**Comment by rahat-yasir** [comment]
To try it on a big image as testing, should I modify the full model code or, training on 128x128 and testing on 600x600 should work ?

**Comment by CongBao** [comment]
Yes, it works with latest codes. You can use the pre-trained (128,128,3) model to process your own images with different shape (e.g. (600,600,3) in your case) and do not have to modify any code.

However, I personally recommend you to do fine-tuning with your own images in specific shape and category (e.g. (600,600,3) pictures about flowers, etc., depending on your requirements). The pre-trained model was trained on some general images that covering plants, animals, buildings and so on, which will not give you desirable results if you only focus on a small area for example only flowers. Also, though the latest code support different shapes in train/test, it is recommended to fine-tuning with images of specific shape before testing, which will give you better outcomes.
